dist: xenial
language: python
python:
  - "3.7"


# safelist
branches:
  only:
    - develop

# Install pipenv then run it to install Pipfile dependencies
before_script:
  - pip install pipenv
  - pipenv install

# env: DJANGO_SETTINGS_MODULE="projet_votes.settings.travis"

services:
  - sqlite3

script:
  - python manage.py test
