# Generated by Django 2.2.1 on 2019-05-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("polls", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="event", old_name="groups", new_name="evt_groups"
        )
    ]
