# Generated by Django 2.2.1 on 2019-05-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190527_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='question',
            new_name='questions',
        ),
    ]
