# Generated by Django 2.2.1 on 2019-05-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190527_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': "Groupe d'utilisateurs"},
        ),
    ]
