# Generated by Django 2.2.1 on 2019-05-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190530_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': "Groupe d'utilisateurs", 'verbose_name_plural': "Groupes d'utilisateurs"},
        ),
    ]
