# Generated by Django 2.2 on 2019-05-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='assemblee-generale'),
            preserve_default=False,
        ),
    ]
