# Generated by Django 2.2.1 on 2019-05-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190530_0920'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventGroup',
        ),
    ]
