# Generated by Django 2.2.1 on 2019-05-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("polls", "0006_delete_eventgroup"),
    ]

    operations = [migrations.RenameModel(old_name="UserGroup", new_name="EventGroup")]
