# Generated by Django 2.2.1 on 2019-05-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polls', '0007_userchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': "Evénements : groupes d'utilisateurs",
                'verbose_name_plural': "Evénements : groupes d'utilisateurs",
            },
        ),
    ]
