# Generated by Django 2.2.1 on 2019-05-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('polls', '0008_eventgroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGroups',
            new_name='EventGroup',
        ),
    ]
