# Generated by Django 2.2.1 on 2019-05-30 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("polls", "0008_auto_20190530_1136")]

    operations = [
        migrations.RenameField(
            model_name="eventgroup", old_name="group", new_name="evt_group"
        )
    ]
