# Generated by Django 2.2.1 on 2019-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0009_auto_20190530_1150")]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="choice_no",
            field=models.IntegerField(default=1),
            preserve_default=False,
        )
    ]
