# Generated by Django 2.2.1 on 2019-05-05 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0009_auto_20190505_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChoice',
            new_name='UserVote',
        ),
    ]
