# Generated by Django 2.2.1 on 2019-05-05 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_auto_20190505_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
