# Generated by Django 2.2.1 on 2019-05-30 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("polls", "0010_choice_choice_no")]

    operations = [
        migrations.CreateModel(
            name="GroupVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votes", models.IntegerField()),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.Choice"
                    ),
                ),
                (
                    "eventgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.EventGroup",
                    ),
                ),
            ],
            options={"verbose_name": "GroupVote", "verbose_name_plural": "GroupVotes"},
        )
    ]
