# Generated by Django 2.2.1 on 2019-05-31 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0011_groupvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="uservote",
            name="proxy_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proxy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupvote", name="votes", field=models.IntegerField(default=0)
        ),
    ]
