# Generated by Django 2.2.1 on 2019-05-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190531_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservote',
            name='proxy_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
