# Generated by Django 2.2.1 on 2019-05-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190506_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservote',
            old_name='as_voted',
            new_name='has_voted',
        ),
    ]
