# Generated by Django 2.2.1 on 2019-05-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190512_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(default=1),
        ),
    ]
