# Generated by Django 2.2.1 on 2019-06-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190606_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='evt_group',
        ),
    ]
