# Generated by Django 2.2.1 on 2019-06-06 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_eventgroup_evt_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupvote',
            options={'verbose_name': 'Vote des utilisateurs', 'verbose_name_plural': 'Votes des utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Résolution'},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_no',
            field=models.IntegerField(verbose_name='numéro de question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='libellé'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='nombre de votes'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='event',
            name='current',
            field=models.BooleanField(default=False, verbose_name='en cours'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(verbose_name="date de l'événement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.CharField(choices=[('MAJ', 'Majorité'), ('PROP', 'Proportionnelle')], default='MAJ', max_length=5, verbose_name='mode de scrutin'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='vote_weight',
            field=models.IntegerField(default=0, verbose_name='poids'),
        ),
        migrations.AlterField(
            model_name='groupvote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice', verbose_name='choix'),
        ),
        migrations.AlterField(
            model_name='groupvote',
            name='eventgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EventGroup', verbose_name="groupe d'utilisateurs"),
        ),
        migrations.AlterField(
            model_name='groupvote',
            name='votes',
            field=models.IntegerField(default=0, verbose_name='nombre de votes'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='confirm_date',
            field=models.DateField(verbose_name='date de confirmation'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to=settings.AUTH_USER_MODEL, verbose_name='récipiendaire'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='proxy_confirmed',
            field=models.BooleanField(default=False, verbose_name='procuration confirmée'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='proxy_date',
            field=models.DateField(verbose_name='date de procuration'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='question',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_no',
            field=models.IntegerField(verbose_name='numéro de résolution'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='texte de la résolution'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EventGroup', verbose_name='groupe'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='vote_weight',
            field=models.IntegerField(default=0, verbose_name='poids du groupe'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='date_vote',
            field=models.DateTimeField(null=True, verbose_name='date du vote'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='has_voted',
            field=models.BooleanField(default=False, verbose_name='a voté'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='résolution'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
    ]
