# Generated by Django 2.2.1 on 2019-06-06 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0020_delete_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='utilisateur'),
        ),
        migrations.RemoveField(
            model_name='eventgroup',
            name='event',
        ),
        migrations.AddField(
            model_name='eventgroup',
            name='event',
            field=models.ManyToManyField(to='polls.Event', verbose_name='événement'),
        ),
    ]
