# Generated by Django 2.2.1 on 2019-06-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0023_auto_20190606_1947"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPoll",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=50)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserPoll",
                "verbose_name_plural": "UserPolls",
                "db_table": "",
                "managed": True,
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="groups",
            field=models.ManyToManyField(to="polls.EventGroup", verbose_name="groupes"),
        ),
        migrations.AlterField(
            model_name="eventgroup",
            name="users",
            field=models.ManyToManyField(
                to=settings.AUTH_USER_MODEL, verbose_name="utilisateurs"
            ),
        ),
        migrations.DeleteModel(name="UserGroup"),
    ]
