# Generated by Django 2.2.1 on 2019-06-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_delete_userpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupvote',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]
