# Generated by Django 2.2.1 on 2019-06-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_groupvote_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupVote',
            new_name='Result',
        ),
    ]
