# Generated by Django 2.2.1 on 2019-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20190608_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procuration',
            name='confirm_date',
            field=models.DateField(null=True, verbose_name='date de confirmation'),
        ),
    ]
