# Generated by Django 2.2.1 on 2019-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0033_auto_20190610_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='host_user',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
