# Generated by Django 2.2.2 on 2019-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0037_auto_20190618_0909")]

    operations = [
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                check=models.Q(question_no__gt=0), name="question_no_gt_0"
            ),
        )
    ]
