# Generated by Django 2.2.2 on 2019-06-18 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_auto_20190618_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
