# Generated by Django 2.2.2 on 2019-06-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("polls", "0039_remove_choice_votes")]

    operations = [
        migrations.AlterField(model_name="event", name="slug", field=models.SlugField())
    ]
