# Generated by Django 2.2.2 on 2019-07-03 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0043_usercomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='users',
            field=models.ManyToManyField(blank=True, to='polls.UserComp', verbose_name='utilisateurs'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='proxy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy', to='polls.UserComp', verbose_name='récipiendaire'),
        ),
        migrations.AlterField(
            model_name='procuration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserComp', verbose_name='utilisateur'),
        ),
        migrations.AlterField(
            model_name='uservote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserComp', verbose_name='utilisateur'),
        ),
    ]
