# Generated by Django 2.2.2 on 2019-07-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0044_auto_20190703_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uservote',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Event', verbose_name='événement'),
            preserve_default=False,
        ),
    ]
