# Generated by Django 2.2.2 on 2019-07-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0045_auto_20190704_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comp_slug',
            field=models.SlugField(default='impuls-ions'),
            preserve_default=False,
        ),
    ]
