# Generated by Django 2.2.2 on 2019-07-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0046_company_comp_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_slug',
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('comp_slug',), name='unique_comp_slug'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_event_slug'),
        ),
    ]
