# Generated by Django 2.2.2 on 2020-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0047_auto_20190705_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomp',
            options={'verbose_name': 'Liens Utilisateurs / Sociétés', 'verbose_name_plural': 'Liens Utilisateurs / Sociétés'},
        ),
        migrations.AddField(
            model_name='usercomp',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='administrateur'),
        ),
        migrations.AlterField(
            model_name='company',
            name='comp_slug',
            field=models.SlugField(verbose_name='slug'),
        ),
    ]
