# Generated by Django 2.2.2 on 2020-04-16 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0048_auto_20200415_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomp',
            name='phone_num',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Format de numéro de téléphone invalide', regex='^0[0-9]([ .-]?[0-9]{2}){4}$')], verbose_name='numéro de téléphone'),
        ),
    ]
