# Generated by Django 2.2.12 on 2020-04-21 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0049_usercomp_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventgroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Company', verbose_name='société'),
            preserve_default=False,
        ),
    ]
