# Generated by Django 2.2.12 on 2021-08-20 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0050_eventgroup_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_groups', models.BooleanField(default=False, verbose_name='administrateur')),
                ('upd_rule', models.BooleanField(default=False, verbose_name='administrateur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Propriétés générales',
                'verbose_name_plural': 'Propriétés générales',
            },
        ),
    ]
