# Generated by Django 2.2.12 on 2021-11-08 08:42

from django.db import migrations


class Migration(migrations.Migration):
    # Force migration
    atomic = False

    dependencies = [
        ('polls', '0053_auto_20210821_0027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventGroup',
            new_name='UserGroup',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='eventgroup',
            new_name='usergroup',
        ),
    ]
