# Generated by Django 2.2.12 on 2021-11-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0054_auto_20211108_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
