# Generated by Django 2.2.12 on 2021-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_auto_20211120_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name="date de l'événement"),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_no',
            field=models.IntegerField(verbose_name='numéro de choix'),
        ),
    ]
